# Generated by Django 2.0.6 on 2018-11-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cardno',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
