# Generated by Django 2.0.6 on 2018-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0002_customer_cardno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='warangal', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.CharField(default='sbi', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='cardtype',
            field=models.CharField(default='visa', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='occup',
            field=models.CharField(default='professor', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historydata',
            name='hrs',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='historydata',
            name='minutes',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='historydata',
            name='seconds',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
