# Generated by Django 2.0.6 on 2018-11-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccp', '0003_auto_20181124_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
